version: '3'

services:
  redis:
    image: redis

  subscriber:
    build:
      context: ./subscriber
    container_name: subscriber
    entrypoint: python app.py
    depends_on:
      - redis

  publisher:
    build:
      context: ./publisher
    container_name: publisher
    ports:
      - '8080:8080'
    entrypoint: uvicorn src.api:app --host 0.0.0.0 --port 8080
    depends_on:
      - redis
